export const ElementTypes = {
    BUMPER: 'bumper',
    BORDER: 'border',
    TRACK_END: 'track_end',
    SWITCH: 'simple_switch',
    APPROACH_SIGNAL: 'as',
    MAIN_SIGNAL: 'ms',
    PROTECTION_SIGNAL: 'ps',
    END_OF_TRAIN_DETECTOR: 'eotd',
    SPEED_LIMIT: 'spl',
    TUNNEL: 'tunnel',
    HALT: 'hlt',
    RTCP: 'rtcp',
    KM_JUMP: 'km_jump',
    LINE_SWITCH: 'line_switch',
    SLOPE: 'slope',
    CROSS: 'cross',
    CTC: 'ctc',
    STATION: 'station',
};

export const ElementTypeLabels = {
    [ElementTypes.BUMPER]: 'Bumper',
    [ElementTypes.BORDER]: 'Border',
    [ElementTypes.TRACK_END]: 'Track End',
    [ElementTypes.SWITCH]: 'Switch',
    [ElementTypes.APPROACH_SIGNAL]: 'Approach Signal',
    [ElementTypes.MAIN_SIGNAL]: 'Main Signal',
    [ElementTypes.PROTECTION_SIGNAL]: 'Protection Signal',
    [ElementTypes.END_OF_TRAIN_DETECTOR]: 'End of Train Detector',
    [ElementTypes.SPEED_LIMIT]: 'Speed Limit',
    [ElementTypes.TUNNEL]: 'Tunnel',
    [ElementTypes.HALT]: 'Halt',
    [ElementTypes.RTCP]: 'RTCP',
    [ElementTypes.KM_JUMP]: 'KM Jump',
    [ElementTypes.LINE_SWITCH]: 'Line Switch',
    [ElementTypes.SLOPE]: 'Slope',
    [ElementTypes.CROSS]: 'Cross',
    [ElementTypes.CTC]: 'CTC',
    [ElementTypes.STATION]: 'Station'
};
